version: "3.3"

services:
  # engine_svc:
  #   build:
  #     context: .
  #     dockerfile: api.Dockerfilenvdia
  #   container_name: engine_svc
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - dev.env
  #   command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - redis
  #     - postgres
  
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    env_file:
      - dev.env
    volumes:
        - redis_data:/data
  
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - dev.env
    ports:
      - 5432:5432
    expose:
      - "5432"
    
  # dozzle:
  #   container_name: logger
  #   image: amir20/dozzle:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 9999:8080
  #   env_file:
  #     - dev.env
  # flower_dashboard:
  #   build:
  #     context: .
  #     dockerfile: worker.Dockerfile
  #   container_name: flower_dashboard
  #   command: celery --broker=redis://redis:6379/0 flower --port=5555
  #   ports:
  #     - 5556:5555
  #   env_file:
  #     - dev.env
  #   depends_on:
  #     - engine_svc
  #     - redis
  #     - postgres


  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    ports:
      - 5540:5540
    expose:
      - "5540"
    volumes:
      - redis_insight_data:/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - dev.env
    volumes:
       - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:5050
    expose:
      - "5050"

volumes:
  redis_data:
  postgres_data:
  redis_insight_data:
  pgadmin_data: